# release workflow
name: Release

# this GitHub action creates a release when a tag that matches the pattern
# "v*" (e.g. v0.1.0) is created
on:
  push:
    tags:
      - "v*"

# releases need permissions to read and write the repository contents
# GitHub considers creating releases and uploading assets as writing contents
permissions:
  contents: write

jobs:
  # run acceptance tests
  tests:
    uses: ./.github/workflows/testacc.yml
  goreleaser:
    # require tests to pass
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # allow goreleaser to access older tag information
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
