name: Acceptance Tests

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - go.mod
      - ".github/workflows/testacc.yaml"
  # allow this workflow to be called from other workflows
  workflow_call:

env:
  GOPROXY: https://proxy.golang.org,direct
  DEBIAN_FRONTEND: noninteractive

jobs:
  testacc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run acceptance tests
        run: make testacc
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          report: true
          chart: true
          amend: true
        if: github.event_name == 'push'
        continue-on-error: true
