name: Acceptance Tests

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.go"
      - go.mod
      - ".github/workflows/testacc.yaml"
  # allow this workflow to be called from other workflows
  workflow_call:

env:
  GOPROXY: https://proxy.golang.org,direct
  DEBIAN_FRONTEND: noninteractive

jobs:
  testacc:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Run acceptance tests
        run: make testacc
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: coverage.out

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: testacc
    permissions:
      contents: read
      actions: read # to download code coverage results from "test" job
      pull-requests: write # write permission needed to comment on PR
    steps:
      - uses: fgrosse/go-coverage-report@v1.2.0
        with:
          coverage-artifact-name: "code-coverage"
          coverage-file-name: "coverage.out"
